#pragma once
#include "raylib.h"
#include <cstdint>
#include <iostream>
#include <ctime>
#include <utility>
#include <vector>
#include <stdint.h>
#include <algorithm>
#include <memory>
#include "definitions.hpp"
#include "gameSettings.hpp"